
import FormField = require('dw/web/FormField')
import FormGroup = require('dw/web/FormGroup');
import FormAction = require('dw/web/FormAction');
// autogeneratedfile

/** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#2)*/
declare class FormFriendList extends FormGroup {
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#4) */
	Id : FormField<string>
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#5) */
	firstName : FormField<string>
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#6) */
	lastName : FormField<string>
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#7) */
	address1 : FormField<string>
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#8) */
	address2 : FormField<string>
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#9) */
	date : FormField<string>
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#10) */
	country : FormField<string>
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#21) */
	states : FormStates
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#23) */
	city : FormField<string>
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#24) */
	zip : FormField<string>
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#26) */
	email : FormField<string>
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#28) */
	phone : FormField<string>
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#31) */
	apply : FormAction
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#32) */
	remove : FormAction
}
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#2)*/
declare class FormProfileCustomer extends FormGroup {
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#4) */
	firstname : FormField<string>
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#13) */
	lastname : FormField<string>
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#22) */
	email : FormField<string>
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#35) */
	emailconfirm : FormField<string>
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#48) */
	phone : FormField<string>
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#57) */
	birthDate : FormField<string>
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#66) */
	addtoemaillist : FormField<boolean>
}
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#2)*/
declare class FormProfileLogin extends FormGroup {
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#73) */
	password : FormField<string>
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#84) */
	passwordconfirm : FormField<string>
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#95) */
	currentpassword : FormField<string>
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#105) */
	newpasswords : FormNewPasswords
}
/** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#2)*/
declare class FormProfile extends FormGroup {
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#3) */
	customer : FormProfileCustomer
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#72) */
	login : FormProfileLogin
}

declare global {
interface SFCCForms {
	friendList: FormFriendList
	profile: FormProfile
}
}


/****** SRFA *******/

interface SfraAction {
    description: string | null;
    label: string | null;
    submitted: boolean | null;
    triggered: boolean | null;
    formType: string;
}

interface SfraFiledOptions {
	checked: boolean,
	htmlValue: string,
	label: string,
	id: string,
	selected: boolean,
	value: string
}

interface SfraFieldBoolean {
	checked: boolean;
	selected: boolean;
}

interface SfraFieldString {
	maxLength: number;
	minLength: number;
	regEx: string
}

interface SfraFieldInteger {
	maxValue: number;
	minValue: number;
}

interface SfraField<T> {
	valid: boolean;
	error: string | null
	readonly attributes: string;
	value: T;
	options: SfraFiledOptions[];
	selectedOption: string;
	formType: string;

	htmlValue: string,
	mandatory: boolean,
	dynamicHtmlName: string
	htmlName: string
}

interface SfraFormBase<T> {
	clear() : void;
	copyFrom(src: object): void;
	toObject(): any;
	valid: boolean;
	base: T
	htmlName: string,
	dynamicHtmlName: string,
	error: string | null,
	attributes: string,
	formType: 'formGroup'
}
/** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#2)*/
interface SfraFormFriendList extends SfraFormBase<FormFriendList> {
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#4) */
	Id : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#5) */
	firstName : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#6) */
	lastName : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#7) */
	address1 : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#8) */
	address2 : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#9) */
	date : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#10) */
	country : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#21) */
	states : SfraFormStates
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#23) */
	city : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#24) */
	zip : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#26) */
	email : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#28) */
	phone : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#31) */
	apply : SfraAction
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\friendList.xml#32) */
	remove : SfraAction
}
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#2)*/
interface SfraFormProfileCustomer {
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#4) */
	firstname : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#13) */
	lastname : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#22) */
	email : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#35) */
	emailconfirm : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#48) */
	phone : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#57) */
	birthDate : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#66) */
	addtoemaillist : SfraField<boolean> & SfraFieldBoolean
}
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#2)*/
interface SfraFormProfileLogin {
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#73) */
	password : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#84) */
	passwordconfirm : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#95) */
	currentpassword : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#105) */
	newpasswords : SfraFormNewPasswords
}
/** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#2)*/
interface SfraFormProfile extends SfraFormBase<FormProfile> {
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#3) */
	customer : SfraFormProfileCustomer
	 /** @source [definition](file:c:\Users\admin\Desktop\newFriendList\Social-Ecom\FriendListModule\cartridges\int_ecomSocial\cartridge\forms\default\profile.xml#72) */
	login : SfraFormProfileLogin
}

declare global {
interface SFRAServerForms {
	getForm(name: 'friendList'): SfraFormFriendList
	getForm(name: 'profile'): SfraFormProfile
}
}

declare global {
interface SRFAForms {
	friendList: SfraFormFriendList
	profile: SfraFormProfile
}
}