
import EnumValue = require('dw/value/EnumValue')
import MarkupText = require('dw/content/MarkupText');
import MediaFile = require('dw/content/MediaFile');

// autogeneratedfile - 'd:\ecomSocialMedia\Social-Ecom\FriendListModule\metadata\main\meta\system-objecttype-extensions.xml'
declare global {
    module ICustomAttributes {

		interface GiftCertificateLineItem {
			/**
			* amount

				amount
			* @group GiftCard - GiftCard
			* @source [attribute](file:d:\ecomSocialMedia\Social-Ecom\FriendListModule\metadata\main\meta\system-objecttype-extensions.xml#97) | [group](file:d:\ecomSocialMedia\Social-Ecom\FriendListModule\metadata\main\meta\system-objecttype-extensions.xml#181)
			*/
			amount: number | null;

			/**
			* First Name of Purchaser
			* 
			* @source [attribute](file:d:\ecomSocialMedia\Social-Ecom\FriendListModule\metadata\main\meta\system-objecttype-extensions.xml#104) 
			*/
			fnameFrom: string | null;

			/**
			* First Name of Recipient
			* 
			* @source [attribute](file:d:\ecomSocialMedia\Social-Ecom\FriendListModule\metadata\main\meta\system-objecttype-extensions.xml#112) 
			*/
			fnameTo: string | null;

			/**
			* Gift Card Certificate Pin
			* 
			* @source [attribute](file:d:\ecomSocialMedia\Social-Ecom\FriendListModule\metadata\main\meta\system-objecttype-extensions.xml#120) 
			*/
			giftCertificatePin: string | null;

			/**
			* imgUrl

				imgUrl
			* @group GiftCard - GiftCard
			* @source [attribute](file:d:\ecomSocialMedia\Social-Ecom\FriendListModule\metadata\main\meta\system-objecttype-extensions.xml#129) | [group](file:d:\ecomSocialMedia\Social-Ecom\FriendListModule\metadata\main\meta\system-objecttype-extensions.xml#187)
			*/
			imgUrl: string | null;

			/**
			* Last Name of Purchaser
			* 
			* @source [attribute](file:d:\ecomSocialMedia\Social-Ecom\FriendListModule\metadata\main\meta\system-objecttype-extensions.xml#137) 
			*/
			lnameFrom: string | null;

			/**
			* Last Name of Recipient
			* 
			* @source [attribute](file:d:\ecomSocialMedia\Social-Ecom\FriendListModule\metadata\main\meta\system-objecttype-extensions.xml#144) 
			*/
			lnameTo: string | null;

			/**
			* note

				note
			* @group GiftCard - GiftCard
			* @source [attribute](file:d:\ecomSocialMedia\Social-Ecom\FriendListModule\metadata\main\meta\system-objecttype-extensions.xml#152) | [group](file:d:\ecomSocialMedia\Social-Ecom\FriendListModule\metadata\main\meta\system-objecttype-extensions.xml#185)
			*/
			note: string | null;

			/**
			* productLineItemUUID

				productLineItemUUID
			* @group GiftCard - GiftCard
			* @source [attribute](file:d:\ecomSocialMedia\Social-Ecom\FriendListModule\metadata\main\meta\system-objecttype-extensions.xml#160) | [group](file:d:\ecomSocialMedia\Social-Ecom\FriendListModule\metadata\main\meta\system-objecttype-extensions.xml#186)
			*/
			productLineItemUUID: string | null;

			/**
			* Transaction ID for an activated gift card
			* 
			* @source [attribute](file:d:\ecomSocialMedia\Social-Ecom\FriendListModule\metadata\main\meta\system-objecttype-extensions.xml#168) 
			*/
			transactionId: string | null;

		}
		interface OrderPaymentInstrument {
			/**
			* 
			* 
			* @source [attribute](file:d:\ecomSocialMedia\Social-Ecom\FriendListModule\metadata\main\meta\system-objecttype-extensions.xml#195) 
			*/
			giftCardId: string | null;

			/**
			* 
			* 
			* @source [attribute](file:d:\ecomSocialMedia\Social-Ecom\FriendListModule\metadata\main\meta\system-objecttype-extensions.xml#201) 
			*/
			giftCardPin: string | null;

			/**
			* Transaction ID for Gift Card
			* 
			* @source [attribute](file:d:\ecomSocialMedia\Social-Ecom\FriendListModule\metadata\main\meta\system-objecttype-extensions.xml#207) 
			*/
			transactionId: string | null;

		}
	}
}

declare global {
	interface IGetCustomPreferenceValue {
		
	}
}